# 监听地址
HOST: 127.0.0.1
# 监听端口，默认6160（616是温迪生日啦~）
PORT: 6160
# 日志等级 INFO, DEBUG, WARNING, ERROR, CRITICAL
LOGLEVEL: INFO
# 日志保留天数
LOG_RETAIN_DAYS: 7
# 是否开启调试模式
DEBUG: False

# 本地音乐目录，可配置多个，示例：
#  - "path/to/Music_dir/"
#  - "C:/Users/Babatous/Music"
MUSIC_DIR:
  - "D:/code/main/Ethereal-Sounds"