name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'  # 路径过滤
  workflow_dispatch:  # 手动触发

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出当前仓库代码
        uses: actions/checkout@v4
        with:
          # 仅拉取必要的历史记录
          fetch-depth: 0

      - name: 安装 Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - args: [--no-frozen-lockfile]

      - name: 构建文档
        run: |
          if [ -d "docs" ]; then
            pnpm install
            pnpm docs:build
          else
            echo "没有找到docs目录，跳过构建"
          fi

      - name: 上传并部署到Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          # 强制推送更新
          force_orphan: true
