name: Vitepress Deploy

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'  # 仅监控docs目录变化
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs  # 工作目录

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: docs/package.json

      - name: 安装pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install --dir docs

      - name: 构建文档
        run: pnpm docs:build

      - name: 初始化Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: vite

      - name: 上传构建产物
        uses: actions/upload-pages@v3
        with:
          path: docs/.vitepress/dist

      - name: 部署到Pages
        uses: actions/deploy-pages@v4
        timeout-minutes: 5
